export enum Routes {
  HOME = "/",
  NEWS = "/news",
  BLOG = "/blog",
  HEALTHY_FOOD = "/healthy-food",
  BODY_CARE = "/body-care",
  BEAUTY = "/beauty",
  DISEASES = "/diseases",
  PSYCHOLOGY = "/psychology",
  INTERVIEWS = "/interviews",
  CHILD_CARE = "/child-care",
  MEDICINE_OF_THE_FUTURE = "/medicine-of-the-future",
  PROGRAM = "/program",
  ANNOUNCEMENTS = "/announcements",
  CULTURE = "/culture",
  SPORT = "/sport",
  TRAVEL_NEWS = "/travel-news",
  RECIPE = "/recipe",
}
